### ISSUE TITLE
Forks which conform to Promises/A+

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/effection.js#36]
Fork objects can sort of act like promises, but it seems like this:

1) Only works for top level forks (I think?)
2) Does not actually conform to [Promises/A+](https://promisesaplus.com/)

In particular, the `then` method should be able to receive two functions, the second of which is called in the error case. I'm not sure if there are other issues. Making forks into proper promises would allow us to `await` them (interestingly this should also make it possible to yield to forks for free, see #28).

I ran into this with our test suite in bigtest/server, where it would be convenient to be able to await forks in setup blocks.

**Comment by cowboyd** [comment]
I also ran into this recently when trying to write a test suite for GitHub Actions https://github.com/thefrontside/actions/blob/testing/test/helpers.ts#L70-L77

There was a lot of annoying glue code to adapt to a promise, and having any fork be `then-able` would be a nice enhancement. Some other benefits and thoughts to note:

1. We could probably unify the `then` model with the `join` method, with parents just `then-ing` their children and resuming once finished. 
2. If we have this interoperability, then there is a clear migration path from async/await -> effection.
3. How does with work with TypeScript typings that expect `Promise`?
