### ISSUE TITLE
Running top level promises may terminate the node process early.

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/effection.js#50]
Given some code like this:

``` typescript
import { fork } from 'effection';

fork(function*() {
  console.log("start");
  yield someController();
  console.log("finish");
});
```

I'd expect this to *always* print `finish`, no matter how controller is implemented, but this is actually not the case! If controller doesn't do anything which creates a listener, then node will shut down before the controller has a chance to finish. This seems a bit surprising to me.

For example listening to an EventEmitter does *not* create a listener. Which is a bit surprising!

IMO, calling `fork` in the global context should prevent node from exiting until the fork completes, but the question is *how* would we implement this?

<details>
<summary>Here's my full example code with an event listener which demonstrates the bug</summary>

``` typescript
import { fork, timeout, Controller } from 'effection';
import { EventEmitter } from 'events';

let someEmitter = new EventEmitter();

function controller(): Controller {
  return (execution) => {
    let resume = () => { execution.resume("foo") };
    someEmitter.on("thing", resume);
    return () => {
      someEmitter.off("thing", resume);
    }
  };
};

let myFork = fork(function*() {
  console.log("start");
  yield controller();
  console.log("finish");
});
```
</details>

**Comment by cowboyd** [comment]
I think that node might be right in that there is no way that the code could actually ever run, because there is no native event OS event, timer, socket data, etc... that could ever run that would  trigger that event, so the process exits.

**Comment by jnicklas** [comment]
Hmm probably. Let's close this then!
