### ISSUE TITLE
What is the proper order of destruction for operations?

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/effection.js#70]
While debugging bigtest server, it seemed to me that the order of destruction for effection operations that I observed in the event of an error or halt might not be ideal. For example, let's say that we have an execution tree with seven processes. These node can represent any stateful could process that contains other stateful process. For example, a websocket server that has active connections, that are reading data:

![Depiction of Execution tree with seven process nested three levels deep](https://user-images.githubusercontent.com/4205/73475774-9d16ff80-4356-11ea-8ea3-fad522d6a6e1.png)

Everything is going along great, until there is an error in one of the leaf nodes. Maybe there was a read error from one of the sockets. We can call this "patient zero" 

![Depiction of the same mostly healthy process tree except an exception has happened on the lower most leaf node](https://user-images.githubusercontent.com/4205/73475938-eff0b700-4356-11ea-88da-becb01c51ab5.png) 

Assuming that there is no error handling in our graph, the constraints of structural concurrency guarantee that this error is going to cause every single process to either fail or halt. If we continue our socket server analogy, the read operation fails, which fails the message handler, which fails the connection handler, which fails the socket server entirely along with every sibling process along the way. The question is, what is the proper order?

As it currently stands, the error will propagate _eagerly_ upwards on the graph, so that the destruction hooks for processes along the path of failure will be run first, and only then, will the children halt and have their destruction hooks run.

![Error propagation flows eagerly up the tree and only after the error has made it to the top are children underneath halted](https://user-images.githubusercontent.com/4205/73476710-62ae6200-4358-11ea-808a-cb60ddbad08b.png)

> **Red** denotes a failed operation, while **Yellow** a halted operation. The number on each picture indicates the order in which the destruction happens.

However, this feels unsafe in the sense that processes lower down the tree can depend on data and other resources further up and so they should never be in a state of being alive while any of the ancestors are failed. In order to guarantee that, then the order of destruction would need to be more from the ground up.

![destruction order depicted in which lower nodes are always completely destroyed before ancestors](https://user-images.githubusercontent.com/4205/73477473-ef0d5480-4359-11ea-869b-f2defa882f6f.png)

I think that we might be (mostly) getting away with this right now because the entire destruction of a tree is 100% synchronous, so there is no opportunity for a yielded child process to "wake up" in a state where its parent was destroyed and it was not. By the time the event could fire that would cause it to awaken, it would have been destroyed. However, it is still a risk if there are synchronous APIS like event emitters, etc... that are created by parents and used downwards.

I think this could be problematic if we start to introduce the capability for asynchronous shutdown. So the really the question is, what is the proper order and for which scenarios?

**Comment by jnicklas** [comment]
To me, the order of destruction should definitely be for the child to "decomission" itself completely, that is I feel that the current behaviour is not what I'd expect.

I think this somewhat connects to the amount of isolation that a child has as well. I am somewhat apprehensive about guaranteeing that an error is raised up immediately when it occurrs. I think we cannot guarantee this in the general case (e.g. async destructors), and so it feels a bit unsafe that it happens *sometimes*. There is something a bit unpredictable about both yield points and errors, in that they can *sometimes* be asynchronous. It's interesting to note for example that the `then` method and `await` syntax are both *always* asynchronous, even if the promise itself is clearly synchronous (e.g. `Promise.resolve(5)`. There is something nice about Effection's synchronous tree of execution, but it's a bit of a double-edged sword, imo.

**Comment by jnicklas** [comment]
This can be closed now that #73 is merged.
